Se genera el Modelo Relacional
school-book/schoolbook-contratos pull request #1
Opened 2020-08-21 02:02 UTC by jorgerdc

Se propone el  modelo relacional para este servicio.

2020-08-21 15:18 UTC, alexJava2015 requested changes

2020-08-21 15:18 UTC, alexJava2015 commented on README.md
> +![Modelo Relacional para contratos](docs/schoolbook-contratos.png)
Tal vez por que no se ha realizado el merge, pero no se muestra la imagen. 
Favor de validar.

2020-08-21 16:21 UTC, vservin approved these changes
Aprobado, verificado en la rama origen.

2020-08-22 15:31 UTC, SamArtGS commented
Aprobado. Mezclando en la rama principal.

2020-08-22 15:31 UTC, SamArtGS approved these changes

2020-08-25 20:27 UTC, jorgerdc commented on README.md
> +![Modelo Relacional para contratos](docs/schoolbook-contratos.png)
SI se debe a que aún no se hace merge.

2020-08-25 20:27 UTC, merged